{% set version = "1.2.0" %}

package:
  name: batchspawner
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/batchspawner/batchspawner-{{ version }}.tar.gz
  sha256: b1924bb4f3a3f527a1e312ecdaff3dbc5acfd91e6b13cf074a62cd74340a2e21

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - batchspawner-singleuser = batchspawner.singleuser:main

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - __unix
    - async_generator >=1.8
    - jinja2
    - jupyterhub-base >=0.9
    - python >=3.5

test:
  imports:
    - batchspawner
  requires:
    - pip
  commands:
    - pip check
    # even this expects a running hub
    # - batchspawner-singleuser --version

about:
  home: https://github.com/jupyterhub/batchspawner
  summary: |
    Batchspawner: A spawner for Jupyterhub to spawn notebooks using batch resource managers.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - consideratio
    - minrk
